server:
  port: 80

spring:
  activemq:
    broker-url: tcp://localhost:61616

  jms:
    template:
      default-destination: bdqn
      # 默认false,true：发布订阅模式false:点对点模式
    pub-sub-domain: true
  rabbitmq:
    port: 5672
    host: 192.168.139.101
    username: root
    password: drg1224605
    virtual-host: /
  kafka:
    bootstrap-servers: 192.168.139.101:9092
    consumer:
      group-id: order

