spring:
  redis:
    host: 192.168.139.101
    port: 6379
    database: 0
    password: drg1224605
    client-type: jedis
    jedis:
      pool:
        max-wait: 1000
        max-idle: 8
        max-active: 8
        min-idle: 0
