

#spring:
#  datasource:
##    url: jdbc:mysql://localhost:3306/bdqn?serverTimezone=UTC
##    hikari:
##      driver-class-name: com.mysql.cj.jdbc.Driver
##      username: root
##      password: drg1224605
#      #    type: com.alibaba.druid.pool.DruidDataSource
#    #    dbcp2:
#    #    tomcat:

# h2\u6570\u636E\u5E93
server:
  port: 80
spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
      url: jdbc:h2:~/test
      hikari:
        driver-class-name: org.h2.Driver
        username: sa
        password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #\u53BB\u9664\u8868\u540D\u524D\u7F00
      table-prefix: t_




