spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bdqn?serverTimezone=UTC
    username: root
    password: drg1224605
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  # \u914D\u5408elasticsearch
  elasticsearch:
    uris: http://localhost:9200

mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
