server:
  port: 80
spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql://localhost:3306/bdqn?serverTimezone=UTC
    username: root
    password: drg1224605
    driver-class-name: com.mysql.cj.jdbc.Driver



jetcache:
  # 查询统计数据的
  statIntervalMinutes: 1
  # 本地方案
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  #远程方案
  remote:
    default:
      type: redis
      host: 192.168.139.101
      port: 6379
      keyConvertor: fastjson
      password: drg1224605
      valueEncode: java
      valueDecode: java
      poolConfig:
        maxTotal: 50
    sms:
      type: redis
      host: 192.168.139.101
      port: 6379
      password: drg1224605
      poolConfig:
        maxTotal: 50



mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl